version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - echo "installing something"

    pre_build:
        commands: 
            - echo "pre build phase"

    build:
        commands:
            - echo "we will run some tests and build"
            - test -f index.html && grep -i app index.html || echo "index.html not found!"

    post_build:
        commands:
            - echo "post build phase"

artifacts:
  files:
    - '**/*'
  name: BuildArtifact
  discard-paths: no
